### ISSUE TITLE
Password not hashed

### ISSUE THREAD

**Issue by curioswati-zz** [curioswati-zz/IIPS-Mobile-App#1]
The passwords are not being hashed while saving in database. Need to look into the setPassword method of User model definition to resolve it.

**Comment by shubham1337** [comment]
I was unable to add Password hashing at the backend, because apparently the function 'add' (in User.js) isn't being called by sequelize during the api call to /User by the app.
So, for the time being, I have added password hashing in the front end using a small (4KB) MD5 hashing library.
Also, Old usernames won't work anymore.

**Comment by curioswati-zz** [comment]
Gives an error in controller: md5 not defined.

**Comment by shubham1337** [comment]
The issue has been resolved by using an MD5 library at the front end.
Closed
